Repository DevValley-team/dev-valley, pull requests merged in 2023-05, with the labels that each got.

#32 [Feature] Swagger 추가, 게시글/댓글 좋아요 기능 구현
  backend/.env.example
  backend/.gitignore
  backend/package.json
  backend/src/common/decorators/api-paginated-response.decorator.ts
  backend/src/common/dtos/page.dto.ts
  backend/src/common/interceptors/serialize-and-set-is-author.interceptor.ts
  backend/src/common/interceptors/serialize.interceptor.ts
  backend/src/config/configuration.ts
  backend/src/main.ts
  backend/src/modules/auth/auth.controller.ts
  backend/src/modules/auth/auth.service.ts
  backend/src/modules/auth/dtos/login-user.dto.ts
  backend/src/modules/auth/dtos/refresh-token.dto.ts
  backend/src/modules/auth/dtos/response/signup-response.dto.ts
  backend/src/modules/auth/dtos/response/token-response.dto.ts
  backend/src/modules/auth/dtos/verify-email.dto.ts
  backend/src/modules/categories/categories.controller.ts
  backend/src/modules/categories/categories.service.ts
  backend/src/modules/categories/dtos/create-category.dto.ts
  backend/src/modules/categories/dtos/response/category-response.dto.ts
  backend/src/modules/categories/dtos/update-category.dto.ts
  backend/src/modules/comments/comments.controller.ts
  backend/src/modules/comments/comments.service.ts
  backend/src/modules/comments/dtos/comment-response.dto.ts
  backend/src/modules/comments/dtos/create-comment.dto.ts
  backend/src/modules/comments/dtos/get-comments.dto.ts
  backend/src/modules/comments/dtos/remove-comment.dto.ts
  backend/src/modules/comments/dtos/response/comment-response.dto.ts
  backend/src/modules/comments/dtos/response/create-comment-response.dto.ts
  backend/src/modules/comments/dtos/update-comment.dto.ts
  backend/src/modules/comments/entities/comment.entity.ts
  backend/src/modules/posts/dtos/create-post.dto.ts
  backend/src/modules/posts/dtos/get-posts.dto.ts
  backend/src/modules/posts/dtos/response/create-post-response.dto.ts
  backend/src/modules/posts/dtos/response/post-details-response.dto.ts
  backend/src/modules/posts/dtos/response/post-summary-response.dto.ts
  backend/src/modules/posts/dtos/responses/post-list-response.dto.ts
  backend/src/modules/posts/dtos/update-post.dto.ts
  backend/src/modules/posts/posts.controller.ts
  backend/src/modules/posts/posts.service.ts
  backend/src/modules/users/dtos/create-user.dto.ts
  backend/src/modules/users/dtos/exists-email.dto.ts
  backend/src/modules/users/dtos/response/user-response.dto.ts
  backend/src/modules/users/dtos/response/user-summary-response.dto.ts
  backend/src/modules/users/dtos/update-user.dto.ts
  backend/src/modules/users/users.controller.ts
  backend/src/modules/users/users.service.ts
  backend/test-utils/comment.http
  backend/test-utils/post.http
  backend/yarn.lock
Labels: 🛠️ 백엔드, 🕹️ 기능

#38 Feature/byungho
  backend/src/common/dtos/page.dto.ts
  backend/src/common/interceptors/serialize-and-set-is-author.interceptor.ts
  backend/src/modules/auth/auth.service.ts
  backend/src/modules/categories/categories.controller.ts
  backend/src/modules/categories/categories.service.ts
  backend/src/modules/categories/dtos/response/category-response.dto.ts
  backend/src/modules/categories/dtos/update-category.dto.ts
  backend/src/modules/categories/entities/category.entity.ts
  backend/src/modules/comments/comments.service.ts
  backend/src/modules/comments/dtos/get-comments.dto.ts
  backend/src/modules/comments/entities/comment.entity.ts
  backend/src/modules/posts/dtos/create-post.dto.ts
  backend/src/modules/posts/dtos/get-posts.dto.ts
  backend/src/modules/posts/dtos/response/post-details-response.dto.ts
  backend/src/modules/posts/dtos/update-post.dto.ts
  backend/src/modules/posts/entities/post.entity.ts
  backend/src/modules/posts/posts.service.ts
  backend/src/modules/users/dtos/response/user-response.dto.ts
  backend/src/modules/users/entities/user.entity.ts
  backend/src/modules/users/users.service.ts
  backend/test-utils/auth.http
  backend/test-utils/category.http
  backend/test-utils/http-client.env.json
  backend/test-utils/post.http
Labels: 🐛 버그, 🛠️ 백엔드, 🕹️ 기능, 🚿 리팩토링

#39 feat: Login
  frontend/.babelrc
  frontend/.gitignore
  frontend/next.config.js
  frontend/package-lock.json
  frontend/package.json
  frontend/server/server.ts
  frontend/src/api/auth.ts
  frontend/src/api/index.ts
  frontend/src/components/Alert/InformTimerAlert.ts
  frontend/src/components/Comment/CommentArea.tsx
  frontend/src/components/Comment/CommentWriter.tsx
  frontend/src/components/GlobalStyle.ts
  frontend/src/components/Layout.tsx
  frontend/src/components/LoginForm.tsx
  frontend/src/components/Modal/TopNavDrawer.tsx
  frontend/src/components/Post/CommunityPosts.tsx
  frontend/src/components/Post/PostContentStyle.tsx
  frontend/src/components/Post/PostEditor.tsx
  frontend/src/components/Post/PostUserProfile.tsx
  frontend/src/components/Seo.tsx
  frontend/src/components/SignupForm.tsx
  frontend/src/components/TopNav.tsx
  frontend/src/constants/api.ts
  frontend/src/constants/index.ts
  frontend/src/constants/session.ts
  frontend/src/middlewares/index.ts
  frontend/src/middlewares/sessions.ts
  frontend/src/pages/_app.tsx
  frontend/src/pages/_document.tsx
  frontend/src/pages/api/hello.ts
  frontend/src/pages/community/[id].tsx
  frontend/src/pages/community/index.tsx
  frontend/src/pages/community/write.tsx
  frontend/src/pages/index.tsx
  frontend/src/pages/login.tsx
  frontend/src/pages/register.tsx
  frontend/src/recoil/index.ts
  frontend/src/styles/styled.d.ts
  frontend/src/styles/theme.ts
  frontend/src/utils/formattedDate.ts
  frontend/tsconfig.server.json
Labels: 🐛 버그, 🔮 프론트, 🕹️ 기능
